#
on:
  schedule:
  - cron: '0 */4 * * *'
  push:
    branches:
    - master
  pull_request:
    paths:
    - .github/workflows/e2e-storybook-workflow.yml
    - scripts/e2e-setup-ci.sh

name: 'E2E Storybook'
jobs:
  chore:
    name: 'Validating Storybook (with a React app)'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: 'Install Node'
      uses: actions/setup-node@master
      with:
        node-version: 14.x

    - name: 'Build the standard bundle'
      run: |
        node ./scripts/run-yarn.js build:cli

    - name: 'Running the integration test'
      run: |
        source scripts/e2e-setup-ci.sh
        yarn dlx create-react-app my-cra && cd my-cra

        # TODO: Remove when fixed upstream
        yarn add -D eslint-config-react-app babel-eslint eslint

        yarn dlx -p @storybook/cli@next sb init --yes

        # TODO: Remove when fixed upstream
        yarn config set "packageExtensions['@storybook/preset-create-react-app@*'].peerDependencies.webpack" "*"
        yarn config set "packageExtensions['@storybook/preset-create-react-app@*'].dependencies['react-refresh']" "*"
        yarn config set "packageExtensions['@storybook/preset-create-react-app@*'].dependencies['webpack-hot-middleware']" "*"
        yarn add webpack@^4 @babel/core prop-types

        yarn build-storybook

